#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
oplus_bsp_tp_ft3658u_spi-y += ft3658u_driver.o
oplus_bsp_tp_ft3658u_spi-y += ft3658u_test.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT3658U_SPI) += oplus_bsp_tp_ft3658u_spi.o
