ccflags-y += -Werror=parentheses

obj-$(CONFIG_OPLUS_CHG_TEST_KIT) += test-kit.o

subdir-ccflags-y += -I$(srctree)/drivers/pinctrl/mediatek
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/gpio
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include

subdir-ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/drivers/misc/mediatek/include
subdir-ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/drivers/power/supply
subdir-ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/drivers/gpu/drm/mediatek/mediatek_v2/
subdir-ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/drivers/power/oplus/test-kit
